title: Documentation - main page
description: Official company documentations
markdown: kramdown
collections:
  docs:
    output: true
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
theme: minima
